class Parameters:

    CHANGE_ATOMIC_ACTION_PROBABILITY = 0
    NOISE_AMOUNT = 0.2
    ADD_NOISE_PROBABILITY = 0.8
    POINTER_PROBABILITY = 0.5
    NEW_LEARNER_PROBABILITY = 0.2
    REMOVE_LEARNER_PROBABILITY = 0.6
    ADD_LEARNER_PROBABILITY = 0.6
    MAX_LEARNER_COUNT = 20
    DATABASE_USER_ID = "postgres"
    DATABASE_PASSWORD = "template!PWD"
    DATABASE_IP = "127.0.0.1"
    DATABASE_PORT = 5432
    DATABASE_NAME = "postgres"
    NUM_LUCKY_BREAKS = 2

    MAX_NUM_STEPS = 1000
    POPULATION_SIZE = 32
    INITIAL_LEARNER_POPULATION_SIZE = 1000
    POPGAP = 0.5
    ENVIRONMENT = 'LunarLander-v2'
    ACTIONS = range(4)
    NUM_OBSERVATIONS = 8
    NUM_HIDDEN_LAYER_NEURONS = 32
    DISCOUNT_RATE = 0.98
    LEARNING_RATE = 0.001
    MAX_INITIAL_TEAM_SIZE = 5
